fig3, ax = plt.subplots(figsize=(8,8))
ax.semilogy(np.abs(exp_cf[1::2]), 'yo', label=r"$a_{n}$ using Integration")
ax.semilogy(np.abs(exp_cf[2::2]), 'ro', label=r"$b_{n}$ using Integration")
ax.semilogy(np.abs(exp_cf_fit[1::2]), 'go', label=r"$a_{n}$ using Least Squares")
ax.semilogy(np.abs(exp_cf_fit[2::2]), 'bo', label=r"$b_{n}$ using Least Squares")
ax.legend()
ax.set_title("Figure 3 : Fourier coefficients of $e^{x}$ (semi-log)")
ax.set_xlabel(r'n$\longrightarrow$')
ax.set_ylabel(r'Magnitude of coeffients$\longrightarrow$')
ax.grid(True)
fig3.savefig(PATH + 'Figure3.png')
